# config/moonshine.yml is loaded both by capistrano and moonshine.
#  The result is the values defined here can be used in `config/deploy.rb` directly
#  and in `app/manifest/application_manifest.rb` via `configuration`

# ruby to install at `cap deploy:setup` time. If you change this value, you
# need to run `cap ruby:upgrade`.
#
# As of time of generating, these are valid values:
# * mri (as installed by Ubuntu)
# * src187
# * ree
# * ree187
# * src192
# * src193
# * src193falcon - This is p327 + falcon patch and provides some serious performance benefits compared to stock 1.9.3.
# * src193railsexpress - This is p448 + the railsexpress patches and in early testing is even faster than just the falcon patch.

:ruby: src200

# Name of your application. Should be something with only alphanumerics, hypens
# and underscores.
:application: tbapp

# Deploy user
:user: rails

# Timezone to set server's time to. Defaults to UTC
#:time_zone: UTC

# Directory where application is deployed to
:deploy_to: /var/www/apps/tbapp

# Primary domain application will be accessed as 
:domain: app.trackingbook.com

# Domain aliases for application. One common use of this is for asset hosts.
#:domain_aliases:
#  - assets1.yourapp.com
#  - assets2.yourapp.com

# Source control management to use. Defaults to git.
# If you change this value, you will need to run: cap vcs:install
#:scm: git
# Reposistory URI for checking out code at deploy time
:repository: git@github.com:electricgraffitti/tbapp.git
#:deploy_via: remote_cache
#
:assets:
  :enabled: true

# Use :app_symlinks to setup directories under public/ that you want to persist
# across deployments. They'll be symlinked to the shared directory.
#:app_symlinks:
#  - system

# Use :shared_config to copy directories straight from your local project
# directory to the server: these are files that you don't have/want in scm.
# Use :shared_config to copy directories straight from your local project
# directory to the server: these are files that you don't have/want in scm.
:shared_config:
  - config/database.yml
  - config/application.yml
  - config/moonshine.yml

# The entries in shared_children are created in #{application}/shared
:shared_children:
- system
- log
- pids
- tmp

# Specify native dependencies of gems. Moonshine comes with some preconfigured
# defaults, but this allows you to add to them. Please file an issue at
# http://github.com/railsmachine/moonshine/issues if there are additional gem
# dependencies Moonshine should know about.
#:apt_gems:
#  :awesomegem:
#    - awesome
#    - libawesome-dev

# Passenger-specific options. Refer to the following templates for details
# about what values are used:
# - vendor/plugins/moonshine/lib/moonshine/manifest/rails/templates/passenger.conf.erb 
# - vendor/plugins/moonshine/lib/moonshine/manifest/rails/templates/passenger.vhost.erb 
:passenger:
  :max_pool_size: 3

# MySQL-specific options. Refer to the following templates for details about
# what values are used:
# - vendor/plugins/moonshine/lib/moonshine/manifest/rails/templates/moonshine.cnf.erb 
:mysql:
  :innodb_buffer_pool_size: 128M
